### PR TITLE
Added GPUImageiOSImageEffect from https://gist.github.com/Ahti/8662879

### PR DESCRIPTION
**Pull request by faceleg**

### CODE REVIEW

**Comment by faceleg** [comment]
Hi @BradLarson, please let me know what I can do to get this one in?

**Comment by r3mus** [comment]
Wondering how this is different from GPUImageiOSBlurFilter.h?

**Comment by BradLarson** [comment]
Yeah, I don't see why we need an entirely different filter from GPUImageiOSBlurFilter, when that could simply be modified with these additions.

**Comment by faceleg** [comment]
I am a moron! Thanks for pointing this out for me.

Shall I look at modifying the GPUUmageiOSBlurFilter with the additions suggested in this PR?

**Comment by BradLarson** [comment]
That'd be greatly appreciated. I think it should just be a matter of modifying or swapping out the last stage in the filter to achieve these slightly different tints.

**Comment by faceleg** [comment]
I'll do so in a separate PR

**Comment by faceleg** [comment]
See #2020

**Pull request closed without merging**
